name: PR checks
on: pull_request

env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag design.ubuntu.com .
      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key design.ubuntu.com
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  lint-scss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint scss
        run: yarn lint-scss

  check-inclusive-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
